import {Module} from '@nestjs/common'
import {CqrsModule} from '@nestjs/cqrs'
import {InfraModule} from '../../infra/InfraModule'
import {
  GetAccountQueryHandler,
  GetBrewerQueryHandler,
  GetBrewingSessionQueryHandler,
  GetCoffeeQueryHandler,
  GetCountryQueryHandler,
  GetCuppingSessionQueryHandler,
  GetEntityPostsQueryHandler,
  GetEvaluationQueryHandler,
  GetFarmQueryHandler,
  GetGrinderQueryHandler,
  GetMeQueryHandler,
  GetPostQueryHandler,
  GetRecipeQueryHandler,
  GetRegionQueryHandler,
  GetRoleQueryHandler,
  GetUserQueryHandler,
  GetVarietyQueryHandler,
  GetViewQueryHandler,
  ListAccountsQueryHandler,
  ListBrewGuidesQueryHandler,
  ListBrewersQueryHandler,
  ListBrewingSessionsQueryHandler,
  ListCoffeesQueryHandler,
  ListCountriesQueryHandler,
  ListCuppingSessionQueryHandler,
  ListEvaluationsQueryHandler,
  ListFarmsQueryHandler,
  ListGrindersQueryHandler,
  ListPostsQueryHandler,
  ListRecipesQueryHandler,
  ListRegionsQueryHandler,
  ListRolesQueryHandler,
  ListUsersQueryHandler,
  ListVarietiesQueryHandler,
  ListViewsQueryHandler,
} from '.'

const handlers = [
  GetAccountQueryHandler,
  GetBrewerQueryHandler,
  GetBrewingSessionQueryHandler,
  GetCoffeeQueryHandler,
  GetCountryQueryHandler,
  GetCuppingSessionQueryHandler,
  GetEntityPostsQueryHandler,
  GetEvaluationQueryHandler,
  GetFarmQueryHandler,
  GetGrinderQueryHandler,
  GetMeQueryHandler,
  GetPostQueryHandler,
  GetRecipeQueryHandler,
  GetRegionQueryHandler,
  GetRoleQueryHandler,
  GetUserQueryHandler,
  GetVarietyQueryHandler,
  GetViewQueryHandler,
  ListAccountsQueryHandler,
  ListBrewGuidesQueryHandler,
  ListBrewersQueryHandler,
  ListBrewingSessionsQueryHandler,
  ListCoffeesQueryHandler,
  ListCountriesQueryHandler,
  ListCuppingSessionQueryHandler,
  ListEvaluationsQueryHandler,
  ListFarmsQueryHandler,
  ListGrindersQueryHandler,
  ListPostsQueryHandler,
  ListRecipesQueryHandler,
  ListRegionsQueryHandler,
  ListRolesQueryHandler,
  ListUsersQueryHandler,
  ListVarietiesQueryHandler,
  ListViewsQueryHandler,
]

@Module({
  imports: [CqrsModule, InfraModule],
  providers: handlers,
  exports: handlers,
})
export class QueryModule {}
