import {Module} from '@nestjs/common'
import {CqrsModule} from '@nestjs/cqrs'
import {InfraModule} from '../../infra/InfraModule'
import {
  AddUserToAccountCommandHandler,
  CreateAccountWithOwnerCommandHandler,
  CreateCoffeeCommandHandler,
  CreateFarmCommandHandler,
  CreateOwnerRoleCommandHandler,
  CreatePostCommandHandler,
  CreateRoleCommandHandler,
  CreateUserCommandHandler,
  CreateVarietyCommandHandler,
  CreateViewCommandHandler,
  DeleteAccountCommandHandler,
  DeleteCoffeeCommandHandler,
  DeleteFarmCommandHandler,
  DeletePostCommandHandler,
  DeleteRoleCommandHandler,
  DeleteUserCommandHandler,
  DeleteVarietyCommandHandler,
  DeleteViewCommandHandler,
  LoginUserCommandHandler,
  LogoutUserCommandHandler,
  RefreshTokenCommandHandler,
  SwitchAccountCommandHandler,
  TogglePostPinCommandHandler,
  UpdateAccountCommandHandler,
  UpdateCoffeeCommandHandler,
  UpdateFarmCommandHandler,
  UpdateMeComandHandler,
  UpdatePostCommandHandler,
  UpdateRoleCommandHandler,
  UpdateUserCommandHandler,
  UpdateUserPasswordCommandHandler,
  UpdateUserRolesCommandHandler,
  UpdateVarietyCommandHandler,
  UpdateViewCommandHandler,
} from '.'

const handlers = [
  AddUserToAccountCommandHandler,
  CreateAccountWithOwnerCommandHandler,
  CreateCoffeeCommandHandler,
  CreateFarmCommandHandler,
  CreateOwnerRoleCommandHandler,
  CreatePostCommandHandler,
  CreateRoleCommandHandler,
  CreateUserCommandHandler,
  CreateVarietyCommandHandler,
  CreateViewCommandHandler,
  DeleteAccountCommandHandler,
  DeleteCoffeeCommandHandler,
  DeleteFarmCommandHandler,
  DeletePostCommandHandler,
  DeleteRoleCommandHandler,
  DeleteUserCommandHandler,
  DeleteVarietyCommandHandler,
  DeleteViewCommandHandler,
  LoginUserCommandHandler,
  LogoutUserCommandHandler,
  RefreshTokenCommandHandler,
  SwitchAccountCommandHandler,
  TogglePostPinCommandHandler,
  UpdateAccountCommandHandler,
  UpdateCoffeeCommandHandler,
  UpdateFarmCommandHandler,
  UpdateMeComandHandler,
  UpdatePostCommandHandler,
  UpdateRoleCommandHandler,
  UpdateUserCommandHandler,
  UpdateUserPasswordCommandHandler,
  UpdateUserRolesCommandHandler,
  UpdateVarietyCommandHandler,
  UpdateViewCommandHandler,
]

@Module({
  imports: [CqrsModule, InfraModule],
  providers: handlers,
  exports: handlers,
})
export class CommandModule {}
