version: '3'

services:
  app:
    ports:
      - 8001:8000
    environment:
      - API_URL=http://gateway-luminate:3000/graphql
    command: yarn workspace @luminate/app run serve --host "0.0.0.0" -p 8000

  identity-schema:
    ports:
      - 3001:3001
    environment:
      - PORT=3001
      - MONGO_URL=mongodb://db:27017/db
    command: yarn workspace @luminate/identity-schema run start

  encyclopedia-schema:
    ports:
      - 3002:3002
    environment:
      - PORT=3002
      - MONGO_URL=mongodb://db:27017/db
    command: yarn workspace @luminate/encyclopedia-schema run start

  brewing-schema:
    ports:
      - 3003:3003
    environment:
      - PORT=3003
      - MONGO_URL=mongodb://db:27017/db
    command: yarn workspace @luminate/brewing-schema run start

  gateway-luminate:
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - SERVER_AUTH_PORT=3001
      - SERVER_ENCYCLOPEDIA_PORT=3002
      - SERVER_BREWING_PORT=3003
      - MONGO_URL=mongodb://db:27017/db
    command: yarn workspace @luminate/gateway-luminate run start
