version: '3.8'

services:
  zookeeper:
    image: wurstmeister/zookeeper

  kafka:
    image: wurstmeister/kafka

  db:
    image: mongo:3.6.17-xenial
    container_name: db

  app:
    build:
      context: .
      dockerfile: packages/frontend/app/Dockerfile
    image: app
    container_name: app

  api:
    build:
      context: .
      dockerfile: packages/backend/api/Dockerfile
    image: api
    container_name: api
    depends_on:
      - db
