version: '3.8'

services:
  zookeeper:
    ports:
      - 2181:2181
    #volumes:
    #- ./kafka/zk/data:/opt/zookeeper-3.4.13/data
    #- ./kafka/zk/conf:/opt/zookeeper-3.4.13/conf

  kafka:
    ports:
      - 9092:9092
    hostname: kafka
    environment:
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LOG_DIRS: /logs
      KAFKA_BROKER_ID: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      #- ./kafka/kafka/data:/logs

  db:
    ports:
      - 27017:27017
    volumes:
      - /var/lib/mongodb:/data/db

  mongo-utils:
    build:
      target: install
    environment:
      - MONGO_URL=mongodb://db:27017/luminate-encyclopedia
    user: 1000:1000
    volumes:
      - ./packages/backend/utils/mongo:/app/packages/backend/utils/mongo
    command: yarn workspace @luminate/mongo-utils run develop

  graphql-utils:
    build:
      target: install
    user: 1000:1000
    volumes:
      - ./packages/backend/utils/graphql:/app/packages/backend/utils/graphql
    command: yarn workspace @luminate/graphql-utils run develop

  app:
    build:
      target: install
    ports:
      - 8003:8000
    environment:
      - API_URL=http://localhost:3000/graphql
    user: 1000:1000
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules
    command: yarn workspace @luminate/app run develop --host "0.0.0.0" --port 8000

  services-shared:
    build:
      context: .
      dockerfile: packages/backend/services/shared/Dockerfile
      target: install
    user: 1000:1000
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules
    command: yarn workspace @luminate/services-shared run develop

  identity-schema:
    build:
      target: install
    ports:
      - 3001:3000
    environment:
      - PORT=3000
      - MONGO_URL=mongodb://db:27017/luminate-identity
      - KAFKA_HOST=kafka:9092
    user: 1000:1000
    depends_on:
      - kafka
    links:
      - kafka
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules
    command: yarn workspace @luminate/identity-schema run develop

  encyclopedia-schema:
    build:
      target: install
    ports:
      - 3002:3000
    environment:
      - PORT=3000
      - MONGO_URL=mongodb://db:27017/luminate-encyclopedia
    user: 1000:1000
    volumes:
      - ./:/app
    command: yarn workspace @luminate/encyclopedia-schema run develop

  brewing-schema:
    build:
      target: install
    ports:
      - 3003:3000
    environment:
      - PORT=3000
      - MONGO_URL=mongodb://db:27017/luminate-brewing
      - KAFKA_HOST=kafka:9092
    user: 1000:1000
    volumes:
      - ./:/app
    command: yarn workspace @luminate/brewing-schema run develop

  gateway-luminate:
    build:
      target: install
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - SERVER_AUTH_URL=http://identity-schema:3000/graphql
      - SERVER_ENCYCLOPEDIA_URL=http://encyclopedia-schema:3000/graphql
      - SERVER_BREWING_URL=http://brewing-schema:3000/graphql
    user: 1000:1000
    volumes:
      - ./:/app
    command: yarn workspace @luminate/gateway-luminate run develop
