version: '3.8'

services:
  mongo-utils:
    build:
      context: .
      dockerfile: packages/backend/mongo/Dockerfile
    image: mongo-utils

  graphql-utils:
    build:
      context: .
      dockerfile: packages/backend/graphql-utils/Dockerfile
    image: graphql-utils
    depends_on:
      - mongo-utils

  db:
    image: mongo:3.6.17-xenial
    container_name: db
    volumes:
      - mongo:/data/db

  app:
    build:
      context: .
      dockerfile: packages/frontend/app/Dockerfile
    image: app
    container_name: app
    restart: unless-stopped

  server-auth:
    build:
      context: .
      dockerfile: packages/backend/server-auth/Dockerfile
    image: server-auth
    container_name: server-auth
    restart: unless-stopped
    depends_on:
      - mongo-utils
      - graphql-utils
    links:
      - db:db
    volumes:
      - mongo:/data/db

  server-encyclopedia:
    build:
      context: .
      dockerfile: packages/backend/server-encyclopedia/Dockerfile
    image: server-encyclopedia
    container_name: server-encyclopedia
    restart: unless-stopped
    depends_on:
      - mongo-utils
      - graphql-utils
    links:
      - db:db
    volumes:
      - mongo:/data/db

  server-sensory-eval:
    build:
      context: .
      dockerfile: packages/backend/server-sensory-eval/Dockerfile
    image: server-sensory-eval
    container_name: server-sensory-eval
    restart: unless-stopped
    depends_on:
      - mongo-utils
      - graphql-utils
    links:
      - db:db
    volumes:
      - mongo:/data/db

  server-gateway:
    build:
      context: .
      dockerfile: packages/backend/server-gateway/Dockerfile
    image: server-gateway
    container_name: server-gateway
    restart: unless-stopped
    depends_on:
      - mongo-utils
      - graphql-utils
      - server-auth
      - server-encyclopedia
      - server-sensory-eval
    links:
      - db:db
      - server-auth
      - server-encyclopedia
      - server-sensory-eval
    volumes:
      - mongo:/data/db

volumes:
  mongo:
    external: true
