version: '3.8'

services:
  zookeeper:
    ports:
      - 2181:2181

  kafka:
    ports:
      - 9092:9092
    hostname: kafka
    environment:
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LOG_DIRS: /logs
      KAFKA_BROKER_ID: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  db:
    ports:
      - 27017:27017
    volumes:
      - /var/lib/mongodb:/data/db

  app:
    build:
      target: install
    ports:
      - 8000:8000
    environment:
      - API_URL=http://localhost:3000/graphql
    user: 1000:1000
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules
    command: yarn workspace @luminate/app run develop --host "0.0.0.0" --port 8000

  api:
    build:
      target: install
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - DB_URL=mongodb://db:27017/luminate
    user: 1000:1000
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules
    command: yarn workspace @luminate/api develop
