version: '3.8'

services:
  zookeeper:
    image: wurstmeister/zookeeper

  kafka:
    image: wurstmeister/kafka

  db:
    image: mongo:3.6.17-xenial
    container_name: db

  mongo-utils:
    build:
      context: .
      dockerfile: packages/backend/utils/mongo/Dockerfile
    image: mongo-utils

  graphql-utils:
    build:
      context: .
      dockerfile: packages/backend/utils/graphql/Dockerfile
    image: graphql-utils
    depends_on:
      - mongo-utils

  app:
    build:
      context: .
      dockerfile: packages/frontend/app/Dockerfile
    image: app
    container_name: app

  identity-schema:
    build:
      context: .
      dockerfile: packages/backend/services/identity/schema/Dockerfile
    image: identity-schema
    container_name: identity-schema
    depends_on:
      - db
      - mongo-utils
      - graphql-utils

  encyclopedia-schema:
    build:
      context: .
      dockerfile: packages/backend/services/encyclopedia/schema/Dockerfile
    image: encyclopedia-schema
    container_name: encyclopedia-schema
    depends_on:
      - db
      - mongo-utils
      - graphql-utils

  sensory-eval-schema:
    build:
      context: .
      dockerfile: packages/backend/services/sensory-eval/schema/Dockerfile
    image: sensory-eval-schema
    container_name: sensory-eval-schema
    depends_on:
      - db
      - mongo-utils
      - graphql-utils

  gateway-luminate:
    build:
      context: .
      dockerfile: packages/backend/gateways/luminate/Dockerfile
    image: gateway-luminate
    container_name: gateway-luminate
    depends_on:
      - identity-schema
      - encyclopedia-schema
      - sensory-eval-schema
