export enum EventType {
  BREWER_CREATED_EVENT = 'BREWER_CREATED_EVENT',
  BREWER_UPDATED_EVENT = 'BREWER_UPDATED_EVENT',
  BREWER_DELETED_EVENT = 'BREWER_DELETED_EVENT',
  GRINDER_CREATED_EVENT = 'GRINDER_CREATED_EVENT',
  GRINDER_UPDATED_EVENT = 'GRINDER_UPDATED_EVENT',
  GRINDER_DELETED_EVENT = 'GRINDER_DELETED_EVENT',
  RECIPE_CREATED_EVENT = 'RECIPE_CREATED_EVENT',
  RECIPE_UPDATED_EVENT = 'RECIPE_UPDATED_EVENT',
  RECIPE_DELETED_EVENT = 'RECIPE_DELETED_EVENT',
}
