export enum CommandType {
  CREATE_BREWER_COMMAND = 'CREATE_BREWER_COMMAND',
  UPDATE_BREWER_COMMAND = 'UPDATE_BREWER_COMMAND',
  DELETE_BREWER_COMMAND = 'DELETE_BREWER_COMMAND',
  CREATE_BREW_GUIDE_COMMAND = 'CREATE_BREW_GUIDE_COMMAND',
  UPDATE_BREW_GUIDE_COMMAND = 'UPDATE_BREW_GUIDE_COMMAND',
  DELETE_BREW_GUIDE_COMMAND = 'DELETE_BREW_GUIDE_COMMAND',
  CREATE_GRINDER_COMMAND = 'CREATE_GRINDER_COMMAND',
  UPDATE_GRINDER_COMMAND = 'UPDATE_GRINDER_COMMAND',
  DELETE_GRINDER_COMMAND = 'DELETE_GRINDER_COMMAND',
  CREATE_RECIPE_COMMAND = 'CREATE_RECIPE_COMMAND',
  UPDATE_RECIPE_COMMAND = 'UPDATE_RECIPE_COMMAND',
  DELETE_RECIPE_COMMAND = 'DELETE_RECIPE_COMMAND',
}
